### ISSUE TITLE
Possible Documentaion error 

### ISSUE THREAD

**Issue by packet-rat** [stucco/docs#1]
In "https://github.com/stucco/docs/wiki/arch-v2" , Section on Output Transport Protocol, Message Options the "DeliveryMode: 1" (as shown)  seems to be in conflict with the statement that follows (DeliveryMode should be 'persistent'.).

The message options should be:

```
DeliveryMode:    1,    // 1=non-persistent, 2=persistent
Timestamp:       time.Now(),
ContentType:     "text/plain",
ContentEncoding: "",
Priority:        1,    // 0-9
HasContent:      true, // boolean
Body:            <payload>,
```

DeliveryMode should be 'persistent'.

**Comment by jgoodall** [comment]
Delivery mode is set to persistent. The documentation will be revised in the near future to match the current architecture.
