### ISSUE TITLE
Links to referenced papers on the https://github.com/stucco/docs/ page don't work

### ISSUE THREAD

**Issue by packet-rat** [stucco/docs#2]
The following links on the https://github.com/stucco/docs/ page don't work:
- https://github.com/stucco/docs/blob/master/presentations/2014.03.28-bridges-cisml
- https://github.com/stucco/docs/blob/master/presentations/2014.05.06-bridges-stucco
- https://github.com/stucco/docs/blob/master/presentations/2014.05.28-bridges

**Comment by jgoodall** [comment]
All links in the README have been fixed (700b749525f68a3871d08682efc9d0dd156fda67)
