### ISSUE TITLE
all Oups, something went wrong ... check your search criterias.

### ISSUE THREAD

**Issue by jtyoui** [stucco/docs#5]
![image](https://user-images.githubusercontent.com/28988355/39236035-2f2df0f8-48aa-11e8-9b10-1f8057677394.png)

**Comment by mikeiannacone** [comment]
Not sure based on that.  Do you have some more info about this?

**Comment by jtyoui** [comment]
running stucco-db-rest-service did not find the environment variable SITU_DB_CONFIG, 
please see my stucco-db-rest-service.conf
[supervisord]
loglevel=warn

[program:stucco-db-rest-service]
command=java -jar target/DBConnectionService-1.0.0.jar
directory=/stucco/graph-db-connection-service
process_name=stucco-db-rest-service
numprocs=1
autostart=true
autorestart=true
priority=500
startretries=10
environment=STUCCO_DB_TYPE=ORIENTDB,STUCCO_DB_CONFIG="/stucco/graph-init/config/orientdb.yml",STUCCO_DB_INDEX_CONFIG="/stucco/graph-init/config/stucco_orientdb_indexing.json"

**Comment by jtyoui** [comment]
Exception in thread "main" java.lang.NullPointerException: Missing environment variable SITU_DB_CONFIG
        at gov.ornl.stucco.DBConnectionService.DBConnectionSingleton.<init>(DBConnectionSingleton.java:50)
        at gov.ornl.stucco.DBConnectionService.DBConnectionApplication.createHttpServer(DBConnectionApplication.java:27)
        at gov.ornl.stucco.DBConnectionService.DBConnectionApplication.<init>(DBConnectionApplication.java:18)
        at gov.ornl.stucco.DBConnectionService.DBConnectionApplication.main(DBConnectionApplication.java:59)

**Comment by jtyoui** [comment]
different bytecode)
JarClassLoader: Warning: org/slf4j/impl/StaticLoggerBinder.class in lib/slf4j-simple-1.7.6.jar is hidden by lib/logback-classic-1.1.2.jar (with different bytecode)
JarClassLoader: Warning: org/slf4j/impl/StaticMarkerBinder.class in lib/slf4j-simple-1.7.6.jar is hidden by lib/logback-classic-1.1.2.jar (with different bytecode)
JarClassLoader: Warning: org/slf4j/impl/StaticMDCBinder.class in lib/slf4j-simple-1.7.6.jar is hidden by lib/logback-classic-1.1.2.jar (with different bytecode)
JarClassLoader: Warning: org/w3c/dom/UserDataHandler.class in lib/jaxen-1.1.6.jar is hidden by lib/xml-apis-1.3.03.jar (with different bytecode)
JarClassLoader: Warning: org/json/CDL.class in lib/org.json-chargebee-1.0.jar is hidden by lib/json-20151123.jar (with different bytecode)
JarClassLoader: Warning: org/json/Cookie.class in lib/org.json-chargebee-1.0.jar is hidden by lib/json-20151123.jar (with different bytecode)
JarClassLoader: Warning: org/json/CookieList.class in lib/org.json-chargebee-1.0.jar is hidden by lib/json-20151123.jar (with different bytecode)
JarClassLoader: Warning: org/json/HTTP.class in lib/org.json-chargebee-1.0.jar is hidden by lib/json-20151123.jar (with different bytecode)
JarClassLoader: Warning: org/json/HTTPTokener.class in lib/org.json-chargebee-1.0.jar is hidden by lib/json-20151123.jar (with different bytecode)
JarClassLoader: Warning: org/json/JSONArray.class in lib/org.json-chargebee-1.0.jar is hidden by lib/json-20151123.jar (with different bytecode)
JarClassLoader: Warning: org/json/JSONException.class in lib/org.json-chargebee-1.0.jar is hidden by lib/json-20151123.jar (with different bytecode)
JarClassLoader: Warning: org/json/JSONML.class in lib/org.json-chargebee-1.0.jar is hidden by lib/json-20151123.jar (with different bytecode)
JarClassLoader: Warning: org/json/JSONObject$1.class in lib/org.json-chargebee-1.0.jar is hidden by lib/json-20151123.jar (with different bytecode)
JarClassLoader: Warning: org/json/JSONObject$Null.class in lib/org.json-chargebee-1.0.jar is hidden by lib/json-20151123.jar (with different bytecode)
JarClassLoader: Warning: org/json/JSONObject.class in lib/org.json-chargebee-1.0.jar is hidden by lib/json-20151123.jar (with different bytecode)
JarClassLoader: Warning: org/json/JSONString.class in lib/org.json-chargebee-1.0.jar is hidden by lib/json-20151123.jar (with different bytecode)
JarClassLoader: Warning: org/json/JSONStringer.class in lib/org.json-chargebee-1.0.jar is hidden by lib/json-20151123.jar (with different bytecode)
JarClassLoader: Warning: org/json/JSONTokener.class in lib/org.json-chargebee-1.0.jar is hidden by lib/json-20151123.jar (with different bytecode)
JarClassLoader: Warning: org/json/JSONWriter.class in lib/org.json-chargebee-1.0.jar is hidden by lib/json-20151123.jar (with different bytecode)
JarClassLoader: Warning: org/json/XML.class in lib/org.json-chargebee-1.0.jar is hidden by lib/json-20151123.jar (with different bytecode)
JarClassLoader: Warning: org/json/XMLTokener.class in lib/org.json-chargebee-1.0.jar is hidden by lib/json-20151123.jar (with different bytecode)

**Comment by mikeiannacone** [comment]
`SITU_DB_CONFIG` is another env variable, which should point to the config file location.

This is something that the install scripts normally set, for example if you're using the `dev_setup` or `demo` repos, however if you're installing each component manually you'll need to set it yourself.  For reference, this is where all the env variables are set in the `dev-setup` repo:
https://github.com/stucco/dev-setup/blob/master/provisioning/site.yml#L77

Here is an example of the config file:
https://github.com/stucco/graph-db-connection/blob/master/config/elasticsearch.yml

**Comment by mikeiannacone** [comment]
Also, I should point out what the purpose of that env var is - this lets stucco read data that `situ` stores in Elasticsearch.  Situ is another project we've been working on here, but since you probably don't have a situ instance, the easiest workaround is just to set up an empty Elasticsearch instance and set up the config file to point to that.

That's a little bit cumbersome, I realize - I just added an issue to create a better fix for it, if you (or anyone else) wants to address it: https://github.com/stucco/graph-db-connection-service/issues/1
